config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root   'books#home'
  get    '/home',          to: 'books#home'
  get    '/new',           to: 'books#new'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy' 


  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :books
 resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :book , optional: true
end

app/models/book.rb
class Book < ApplicationRecord
	  before_save { self.title = title.downcase }
	valid_date_regex= /\d{4}(\.|-)\d{2}(\.|-)\d{2}/
	has_many :authors , dependent: :destroy
	accepts_nested_attributes_for :authors , allow_destroy: true
	validates :title ,presence: true ,length: {maximum: 50},uniqueness: { case_sensitive: false }
	validates :publisher ,presence: true ,length: {maximum: 50}
	validates :isbn ,presence: true,length: {maximum: 20},uniqueness: { case_sensitive: false }
	validates :publishing_date, presence: true,format: {with: valid_date_regex}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def home
  end

  def show
  	@book=Book.find(params[:id])
  end

  def new
  	@book=Book.new
  	@book.authors.build
  end

  def create
  	@book=Book.new(book_params)
  	if @book.save
      flash[:success]="new book is added"
  		redirect_to @book

  	else
  		render 'new'
  	end
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    
  end

  private

    def book_params
      params.require(:book).permit(:title, :publisher, :isbn,
                                   :publishing_date , :authors_attributes => [:id, :name])
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		if params[:session][:username]== "root" && params[:session][:password]=="root"
			log_in
			redirect_to root_path
		else
		 	flash.now[:danger] = 'Invalid username/password combination'
		 	render 'new'
		end
	 end

	def destroy
		log_out
		redirect_to root_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in 
		session[:login]=true
	end

	def logged_in?
		session[:login]
	end

	def log_out
		session.delete(:username)
		session.delete(:password)
		session[:login]= false
	end
end

app/views/books/edit.html.erb
<%provide(:title, 'update')%>
<h1>Update book</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@book) do |f| %>

  		<%= render 'shared/error_messages' %>

  		<%=f.label :title%>
  		<%=f.text_field :title , class: 'form-control'%>

  		<%=f.label :publisher%>
  		<%=f.text_field :publisher , class: 'form-control'%>

  		<%=f.label :isbn%>
  		<%=f.text_field :isbn , class: 'form-control'%>

  		<%=f.label :publishing_date%>
  		<%=f.date_field :publishing_date , class: 'form-control'%>

        

  		<%=f.label :Authors%>
		<%@book.authors.each do |p|%>
	        <%= f.fields_for p do |ff| %>
	  		<div>
	    		<%= ff.label :name %>
	    		<%= ff.text_field :name %>
	  		</div>
		<% end %>

		<% end %>

  		<%= submit_tag "Add author", :type => 'button', :id => 'addAuthor', 
          :onclick => 'addAuthorField()' %> 
     <div id="authorHeader" style="display:none">Address information:  </div>
   
 
      <ul id="myList">
      </ul>

  
    <%=f.submit "update book" ,class: "btn btn-primary" %>
  		
  	<%end%>

</div>

app/views/books/home.html.erb
<%provide(:title, 'Home')%>

<div class="center jumbotron">
<h1> Welcome to BOOK ONLINE STORE </h1>
</div>

app/views/books/new.html.erb
<%provide(:title, 'New')%>
<h1>NEW BOOK</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@book) do |f| %>

  		<%= render 'shared/error_messages' %>

  		<%=f.label :title%>
  		<%=f.text_field :title , class: 'form-control'%>

  		<%=f.label :publisher%>
  		<%=f.text_field :publisher , class: 'form-control'%>

  		<%=f.label :isbn%>
  		<%=f.text_field :isbn , class: 'form-control'%>

  		<%=f.label :publishing_date%>
  		<%=f.date_field :publishing_date , class: 'form-control'%>

  		<%= submit_tag "Add author", :type => 'button', :id => 'addAuthor', 
          :onclick => 'addAuthorField()' %> 
     <div id="authorHeader" style="display:none">Address information:  </div>
   
 
      <ul id="myList">
      </ul>

  
    <%=f.submit "create new book" ,class: "btn btn-primary" %>

  	<%end%>

</div>

app/views/books/show.html.erb
<%provide(:title,@book.title)%>
<div class="row">
	 <aside class="col-md-4">
	 	  <section class="user_info">
	 	  	<h1>
				<%=@book.title%> book
			</h1>
			<h2>publisher : <aside class="color"><%=@book.publisher%> </aside><br>
			    ISBN : <aside class="color"><%=@book.isbn%></aside> <br>
			    publishing date :<aside class="color"> <%=@book.publishing_date%></aside><br>
			    Authors :
			    <%@authors=@book.authors.all%>
				<%@authors.each do |f|%><br><aside class="color">
					<%=f.name%>
				<%end%>
			   </aside>
			</h2>
		</section>
	</aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
        <%= link_to "BOOK ONLINE STORE",root_path , id: "logo" %>
		
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<div class="input-group">
				    <input type="text" class="form-control" placeholder="Search">
				    <div class="input-group-btn">
				      <button class="btn btn-default" type="submit" >
				        <i class="glyphicon glyphicon-search"></i>
				      </button>
				    </div>
          </div>
        </li>
				<li><%= link_to "Home", root_path %></li>

				<%if logged_in?%>
					<li><%= link_to "log out", logout_path, method: :delete%></li>
				<% else %>
					<li><%= link_to "login",login_path %></li>
				<% end %>

			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title) %> | Book online store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

  		 <%= yield %>
  	</div>
   
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@book.errors.count, "error") %>.
    </div>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>